# Generated by Django 4.0.8 on 2022-10-31 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='widecity_shopping.orders')),
            ],
        ),
    ]
