# Generated by Django 4.0.8 on 2022-10-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0002_wallet_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet_history',
            name='user_id',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
