# Generated by Django 4.0.8 on 2022-11-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0004_wallet_history_debit_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_month',
            field=models.CharField(default=11, max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_month',
            field=models.CharField(default=11, max_length=50),
        ),
    ]
