# Generated by Django 4.0.8 on 2022-11-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0005_alter_orders_order_day_alter_orders_order_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image_1',
            field=models.ImageField(upload_to='image_1_of_products'),
        ),
    ]
