# Generated by Django 4.0.8 on 2022-11-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0007_rename_arrival_date_products_manufacturing_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
