# Generated by Django 4.0.8 on 2022-11-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0008_alter_products_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='products',
            name='total_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='users',
            name='signup_day',
            field=models.CharField(default=4, max_length=50),
        ),
    ]
