# Generated by Django 4.0.8 on 2022-11-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('widecity_shopping', '0009_alter_orders_order_day_alter_products_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_month',
            field=models.IntegerField(default=11, max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='Order_year',
            field=models.IntegerField(default=2022, max_length=100),
        ),
    ]
